### ISSUE TITLE
rdf box with a geometry rdf type and a non geometry content

### ISSUE THREAD

**Issue by ebremer** [openlink/virtuoso-opensource#195]
Running this command:
`ttlp ('@prefix virtrdf: http://www.openlinksw.com/schemas/virtrdf# . @prefix geo: http://www.w3.org/2003/01/geo/wgs84_pos# . _:wow geo:geometry "POLYGON((0 0, 10 0, 20 0, 500 0, 0 0))"^^virtrdf:Geometry .','','http://www.whatever.com',0);`

Yields this error:
`**\* Error 42000: [Virtuoso Driver][Virtuoso Server]RDFGE: rdf box with a geometry rdf type and a non geometry content`
`at line 7 of Top-Level:`
` ttlp ('@prefix virtrdf: http://www.openlinksw.com/schemas/virtrdf# . @prefix geo: http://www.w3.org/2003/01/geo/wgs84_pos# . _:wow geo:geometry "POLYGON((0 0, 10 0, 20 0, 500 0, 0 0))"^^virtrdf:Geometry .','','http://www.whatever.com',0)`

**Comment by HughWilliams** [comment]
Hi Erich,

I presume this is the same issue you posted on the VOS mailing list?

Development are working on finalising the implementation of the `ST_Transform` function to the changing from one coordinate system to another, which should hopefully then enable your dataset to be loaded.

**Comment by ebremer** [comment]
Hi Hugh,

Yes, I had spoke to Ted T. in Boston last week and he encouraged me to log it here on Github.

**Comment by HughWilliams** [comment]
Yes, Ted mentioned having spoken to you ...

Will notify you when development have finalised the `ST_transform()` function and it is available in open source ...

**Comment by openlink** [comment]
A patch for this 'rdf box with a geometry rdf type and a non geometry content' has been pushed to develop/7

please let us know if this solves your issue.

**Comment by ebremer** [comment]
Great!  I'm compiling it now.  - Erich

**Comment by ebremer** [comment]
With the above example, I get this error:

```
ttlp ('@prefix virtrdf: http://www.openlinksw.com/schemas/virtrdf# . @prefix geo: http://www.w3.org/2003/01/geo/wgs84_pos# . _:wow geo:geometry "POLYGON((0 0, 10 0, 20 0, 500 0, 0 0))"^^virtrdf:Geometry .','','http://www.whatever.com',0)
SQL> ttlp ('@prefix virtrdf: http://www.openlinksw.com/schemas/virtrdf# . @prefix geo: http://www.w3.org/2003/01/geo/wgs84_pos# . _:wow geo:geometry "POLYGON((0 0, 10 0, 20 0, 500 0, 0 0))"^^virtrdf:Geometry .','','http://www.whatever.com',0);

**\* Error 37000: [Virtuoso Driver][Virtuoso Server]SP029: TURTLE RDF loader, line 1: Invalid characters in local part of QName; this error can be suppressed by parser flags at http://www.openlinksw.com/schemas/virtrdf# processed pending to here.
at line 2 of Top-Level:
ttlp ('@prefix virtrdf: http://www.openlinksw.com/schemas/virtrdf# . @prefix geo: http://www.w3.org/2003/01/geo/wgs84_pos# . _:wow geo:geometry "POLYGON((0 0, 10 0, 20 0, 500 0, 0 0))"^^virtrdf:Geometry .','','http://www.whatever.com',0)
SQL>
```

**Comment by ebremer** [comment]
I forgot the brackets, I still get:
```
 ttlp ('@prefix virtrdf: http://www.openlinksw.com/schemas/virtrdf# . @prefix geo: http://www.w3.org/2003/01/geo/wgs84_pos# . _:wow geo:geometry "POLYGON((0 0, 10 0, 20 0, 500 0, 0 0))"^^virtrdf:Geometry .','','http://www.whatever.com',0);

**\* Error 42000: [Virtuoso Driver][Virtuoso Server]RDFGE: rdf box with a geometry rdf type and a non geometry content
at line 19 of Top-Level:
ttlp ('@prefix virtrdf: http://www.openlinksw.com/schemas/virtrdf# . @prefix geo: http://www.w3.org/2003/01/geo/wgs84_pos# . _:wow geo:geometry "POLYGON((0 0, 10 0, 20 0, 500 0, 0 0))"^^virtrdf:Geometry .','','http://www.whatever.com',0)
```

**Comment by HughWilliams** [comment]
I have recreated attempting to load that geometry and reported to development to look into, see the following:
```
SQL> ttlp ('@prefix virtrdf: http://www.openlinksw.com/schemas/virtrdf# .
@prefix geo: http://www.w3.org/2003/01/geo/wgs84_pos# . _:wow geo:geometry
"POLYGON((0 0, 10 0, 20 0, 500 0, 0 0))"^^virtrdf:Geometry
.','','http://www.whatever.com',0);

**\* Error 42000: VD [Virtuoso Server]RDFGE: rdf box with a geometry rdf type
and a non geometry content
in
rdf_box:(BIF),
DB.DBA.TTLP_RL_TRIPLE_L([executable]/ttlpv.sql:255),
rdf_load_turtle:(BIF),
DB.DBA.TTLP_V([executable]/ttlpv.sql:554),
DB.DBA.TTLP([executable]/sparql.sql:2876),
<Top Level>
at line 41 of Top-Level:
ttlp ('@prefix virtrdf: http://www.openlinksw.com/schemas/virtrdf# . @prefix
geo: http://www.w3.org/2003/01/geo/wgs84_pos# . _:wow geo:geometry
"POLYGON((0 0, 10 0, 20 0, 500 0, 0 0))"^^virtrdf:Geometry
.','','http://www.whatever.com',0)
SQL> 
```
whereas the following you provided previously loads successfully:
```
SQL> ttlp ('@prefix virtrdf: http://www.openlinksw.com/schemas/virtrdf# .
@prefix geo: http://www.w3.org/2003/01/geo/wgs84_pos# . _:wow geo:geometry
"POLYGON((1 2, 6 1, 9 3, 3 6, 1 2))"^^virtrdf:Geometry
.','','http://www.whatever.com',0);

Done. -- 1 msec.
SQL>
```
Server version:
```
SQL> status('');
REPORT
VARCHAR

---

OpenLink Virtuoso  Server
Version 07.10.3211-pthreads for Linux as of Jul 12 2014 
Started on: 2014-07-12 22:58 GMT+2
```

**Comment by ebremer** [comment]
Thanks Hugh!  - Erich

**Comment by HughWilliams** [comment]
HI Erich,

The fix for the `ST_Transform()` enabling the transformation between co-ordinate system is now in place in the Virtuoso `v7vasttrack` open source branch. A first draft of documentation detailing how the necessary Virtuoso binary and Proj4 Plugin used for the transformation can be build and test is available from the following dropbox location:

```
https://dl.dropboxusercontent.com/u/106414290/VirtuosoProj4Plugin.pdf
```

Please let me know if this works for you also following the instructions in the document.

**Comment by ebremer** [comment]
Thanks Hugh! I will let you know.  - Erich

**Comment by ebremer** [comment]
One error in pdf:
`"git clone https://github.com/v7fasttrack/virtuosoopensource"`
should be
`"git clone https://github.com/v7fasttrack/virtuosoopensource.git"`

**Comment by HughWilliams** [comment]
thanks I have corrected it ...

**Comment by ebremer** [comment]
It cannot find the plugin with the load line:
`LoadPath                       = ./plugins`
nor will it find it with:
`/opt/virtuoso/lib/virtuoso/hosting`
which is where the files seem to be.
Log says:
```
13:27:16 { Loading plugin 2: Type `plain', file`v7proj4' in `/opt/virtuoso/lib/virtuoso/hosting'
13:27:16   FAILED  plugin 2: libproj.so.0: cannot open shared object file: No such file or directory }
```

**Comment by HughWilliams** [comment]
Was the `v7proj4` plugin built during the compile, i.e., does it exist in `~/libsrc/plugin/.libs/v7proj4`?

`LoadPath` should point to the directory where the plugin resides, so `./plugins` assumes such a directory resides in the directory hosting the database

**Comment by ebremer** [comment]
seems to exists:
```
ls -lt /root/virtuoso-opensource/libsrc/plugin/.libs
total 340
lrwxrwxrwx. 1 root root    13 Jul 29 12:54 v7proj4.la -> ../v7proj4.la
-rw-r--r--. 1 root root   942 Jul 29 12:54 v7proj4.lai
-rw-r--r--. 1 root root 48468 Jul 29 12:54 v7proj4.a
-rwxr-xr-x. 1 root root 44745 Jul 29 12:54 v7proj4.so
-rw-r--r--. 1 root root    38 Jul 29 12:54 v7proj4.ver
lrwxrwxrwx. 1 root root    19 Jul 29 12:54 plugin_sample.la -> ../plugin_sample.la
-rw-r--r--. 1 root root 25386 Jul 29 12:54 plugin_sample.a
lrwxrwxrwx. 1 root root    15 Jul 29 12:54 libplugin.la -> ../libplugin.la
-rw-r--r--. 1 root root 58228 Jul 29 12:54 libplugin.a
-rw-r--r--. 1 root root 14456 Jul 29 12:54 v7proj4_la-v7proj4_plugin.o
-rw-r--r--. 1 root root 47296 Jul 29 12:54 libplugin_la-export_gate_virtuoso.o
-rw-r--r--. 1 root root 22640 Jul 29 12:54 plugin_sample_la-import_gate_virtuoso.o
-rw-r--r--. 1 root root 22640 Jul 29 12:54 v7proj4_la-import_gate_virtuoso.o
-rw-r--r--. 1 root root  9440 Jul 29 12:54 v7proj4_la-sql_v7proj4.o
-rw-r--r--. 1 root root  2384 Jul 29 12:54 plugin_sample_la-plugin_sample.o
lrwxrwxrwx. 1 root root    20 Jul 29 12:54 hosting_sample.la -> ../hosting_sample.la
-rw-r--r--. 1 root root  2970 Jul 29 12:54 hosting_sample.a
-rw-r--r--. 1 root root  1848 Jul 29 12:54 libplugin_la-gate_virtuoso_stubs.o
-rw-r--r--. 1 root root  3856 Jul 29 12:54 libplugin_la-plugin_unix.o
-rw-r--r--. 1 root root  2600 Jul 29 12:54 hosting_sample_la-hosting_sample.o
-rw-r--r--. 1 root root  3288 Jul 29 12:54 libplugin_la-plugin.o
-rw-r--r--. 1 root root  1021 Jul 29 12:54 libplugin_la-dlf.o
```

**Comment by ebremer** [comment]
Hi Hugh, I tried a few different ways, but I still get the following error:
```
virtuoso-t -f
17:16:18 { Loading plugin 2: Type `plain', file`v7proj4' in `/opt/virtuoso/lib/virtuoso/hosting'
17:16:18   FAILED  plugin 2: libproj.so.0: cannot open shared object file: No such file or directory }
17:16:18 OpenLink Virtuoso Universal Server
```
And the v7proj plugin appears to be present 
```
ls -lt /opt/virtuoso/lib/virtuoso/hosting
total 96
-rw-r--r--. 1 root root 48468 Aug  5 17:12 v7proj4.a
-rwxr-xr-x. 1 root root   942 Aug  5 17:12 v7proj4.la
-rwxr-xr-x. 1 root root 44745 Aug  5 17:12 v7proj4.so
```
And my virtuoso contain the following entry:
```
[Plugins]
LoadPath                        = /opt/virtuoso/lib/virtuoso/hosting
Load2                           = plain, v7proj4
```
Suggestions? -= Erich

**Comment by ebremer** [comment]
And `libproj.so.0` exists at:
```
 ls -lt /usr/local/lib/
drwxr-xr-x. 2 root root   4096 Jul 29 12:44 pkgconfig
-rw-r--r--. 1 root root 836006 Jul 29 12:44 libproj.a
-rwxr-xr-x. 1 root root    919 Jul 29 12:44 libproj.la
lrwxrwxrwx. 1 root root     16 Jul 29 12:44 libproj.so -> libproj.so.0.7.0
lrwxrwxrwx. 1 root root     16 Jul 29 12:44 libproj.so.0 -> libproj.so.0.7.0
-rwxr-xr-x. 1 root root 437465 Jul 29 12:44 libproj.so.0.7.0
```

**Comment by HughWilliams** [comment]
Strange as I would expect `/usr/local/lib` to be a default location searched for required libs? You could try setting the `LD_LIBRARY_PATH` env variable to point to `/usr/local/lib` and for this location to be searched for definite when starting Virtuoso?

**Comment by ebremer** [comment]
That was it:
```
09:42:56 { Loading plugin 1: Type `plain', file`v7proj4' in `/opt/virtuoso/lib/virtuoso/hosting'
09:42:56   plain version 3211 from OpenLink Software
09:42:56   Cartographic Projections support based on Frank Warmerdam's proj4 library
09:42:56   SUCCESS plugin 1: loaded from /opt/virtuoso/lib/virtuoso/hosting/v7proj4.so }
09:42:56 OpenLink Virtuoso Universal Server
```
Let me test it now. - Erich

**Comment by HughWilliams** [comment]
Good to hear that worked, will have to make a note of the need for the `libproj.so.0` lib to be in a location where it can be found or set `LD_LIBRARY_PATH` to its location ...

**Comment by ebremer** [comment]
I get a `Table DB.DBA.SYS_V7PROJ4_SRIDS already exists` error when executing the `create table DB.DBA.SYS_V7PROJ4_SRIDS` as per the pdf instructions.  - Erich
```
create table DB.DBA.SYS_V7PROJ4_SRIDS (
Type the rest of statement, end with a semicolon (;)> SR_ID integer,
Type the rest of statement, end with a semicolon (;)> SR_FAMILY varchar not null,
Type the rest of statement, end with a semicolon (;)> SR_TAG varchar,
SR_ORIGIN varchar not null,
SR_IRI IRI_ID_8,
Type the rest of statement, end with a semicolon (;)> Type the rest of statement, end with a semicolon (;)> Type the rest of statement, end with a semicolon (;)> SR_PROJ4_STRING varchar not null,
Type the rest of statement, end with a semicolon (;)> SR_WKT varchar,
Type the rest of statement, end with a semicolon (;)> SR_COMMENT varchar,
Type the rest of statement, end with a semicolon (;)> SR_PROJ4_XML any,
Type the rest of statement, end with a semicolon (;)> primary key (SR_ID, SR_FAMILY) );

**\* Error 42S01: VD [Virtuoso Server]SQ016: Table DB.DBA.SYS_V7PROJ4_SRIDS already exists
in lines 84-94 of Top-Level:
#line 84 "(console)"
create table DB.DBA.SYS_V7PROJ4_SRIDS (
SR_ID integer,
SR_FAMILY varchar not null,
SR_TAG varchar,
SR_ORIGIN varchar not null,
SR_IRI IRI_ID_8,
SR_PROJ4_STRING varchar not null,
SR_WKT varchar,
SR_COMMENT varchar,
SR_PROJ4_XML any,
primary key (SR_ID, SR_FAMILY) )
SQL>
```

**Comment by ebremer** [comment]
Looking ahead, there was an access error to the proj folder which I fixed by adding the access permission to the `virtuoso.ini` file.  Also, in Centos (at least, and perhaps also RHEL which Centos essentially is), proj installs to `/usr/local/share` and not `/usr/share`.  I soft linked `/usr/share/proj` to `/usr/local/share/proj` to avoid any other problems.

**Comment by ebremer** [comment]
These two examples are working:
`select st_transform (st_geomfromtext('POLYGON((-16 20.25,-16.1 20.35,-15.9 20.35,-16 20.25))'), 1, '+proj=latlong +ellps=clrk66','+proj=merc +ellps=clrk66 +lat_ts=33');`

`SELECT ST_AsText(ST_Transform(ST_GeomFromText('POLYGON((743238 2967416,743238 2967450, 743265 2967450,743265.625 2967416,743238 2967416))',2249),4326)) As wgs_geom;`

however, the original insertion does not:
```
ttlp ('@prefix virtrdf: http://www.openlinksw.com/schemas/virtrdf# . @prefix geo: http://www.w3.org/2003/01/geo/wgs84_pos# . _:wow geo:geometry "POLYGON((0 0, 10 0, 20 0, 500 0, 0 0))"^^virtrdf:Geometry .','','http://www.whatever.com',0);

**\* Error 42000: VD [Virtuoso Server]RDFGE: rdf box with a geometry rdf type and a non geometry content
at line 48 of Top-Level:
ttlp ('@prefix virtrdf: http://www.openlinksw.com/schemas/virtrdf# . @prefix geo: http://www.w3.org/2003/01/geo/wgs84_pos# . _:wow geo:geometry "POLYGON((0 0, 10 0, 20 0, 500 0, 0 0))"^^virtrdf:Geometry .','','http://www.whatever.com',0)
```

**Comment by HughWilliams** [comment]
OK, if the `DB.DBA.SYS_V7PROJ4_SRIDS` is auto created now all the better. My build server is CentOS 6.2 and proj is installed in `/usr/local/share/proj`, but we can make a note of both locations.

I am checking with development how the `SRID` can be changed  to `ST_Transform()` can be used to enable the `ttlp` load to be successful, as this is what was indicated would be required for this to work from our discussion on the VOS mailing list, which I just looked up.

Note also in the `develop/7` branch there is an update to return a more meaningful error when loading your data, indicating it is out of range:
```
SQL> ttlp ('@prefix virtrdf: http://www.openlinksw.com/schemas/virtrdf# . @prefix geo: http://www.w3.org/2003/01/geo/wgs84_pos# . _:wow geo:geometry "POLYGON((0 0, 10 0, 20 0, 500 0, 0 0))"^^virtrdf:Geometry .','','http://www.whatever.com',0);

**\* Error 22023: VD [Virtuoso Server]GEO11: The point coordinates are spherical degrees and the longitude is out of range -270..450 (near row 1 col 31 of 'POLYGON((0 0, 10 0, 20 0, 500 0, 0 0))')
in
__xqf_str_parse_to_rdf_box:(BIF),
DB.DBA.TTLP_RL_TRIPLE_L([executable]/ttlpv.sql:225),
rdf_load_turtle:(BIF),
DB.DBA.TTLP_V([executable]/ttlpv.sql:554),
DB.DBA.TTLP([executable]/sparql.sql:2876),
<Top Level>
at line 1 of Top-Level:
ttlp ('@prefix virtrdf: http://www.openlinksw.com/schemas/virtrdf# . @prefix geo: http://www.w3.org/2003/01/geo/wgs84_pos# . _:wow geo:geometry "POLYGON((0 0, 10 0, 20 0, 500 0, 0 0))"^^virtrdf:Geometry .','','http://www.whatever.com',0)
SQL>
```
So have requested this be pushed to `v7fasttrack` as it doesn't appear to be there yet ...

**Comment by yonyonson** [comment]
Hei Hugh!

Do we still have to get Virtuoso from `fasttrack` repo in order to compile `proj4` plugin, or was it integrated in `stable/7` or `develop/7`?

**Comment by yonyonson** [comment]
Thing have tried to compile `proj4` plugin from `fasttrack` version of Virtuoso as described earlier in the ticket, but have got only as far as this ticket: #301 . It is resolved in `7/develop`, but `fasttrack` can't be merged with in automatically. I am guessing it's due to some newer version of the components used.

I have tried compilation with Cent OS 6.6, 7.0 and Ubuntu 14.04 LTS, all end up in #301 .

**Comment by HughWilliams** [comment]
@yonyonson: Yes, the `proj4` plugin still has to be built form the v7 `fasttrack` plugin currently ...

What is the problem from #301 that you are having, as I did think there was an actual fix for it as @jplu reset his repo to resolve the problem in the end?

**Comment by akuckartz** [comment]
@ebremer How was this resolved?
