### ISSUE TITLE
Problem to load Geometry data

### ISSUE THREAD

**Issue by jplu** [openlink/virtuoso-opensource#360]
Hi,

I use the latest version of the develop/7 branch and I have a problem to load Geometry data through virtjena. Data such as:

```
<http://data.linkedevents.org/location/bikepark/146/geometry> <http://www.w3.org/2003/01/geo/wgs84_pos#geometry> "POINT(9.2027395963669 45.4480098982521)"^^http://www.opengis.net/ont/geosparql#wktLiteral
```

Throw me this exception:

```
Exception in thread "main" com.hp.hpl.jena.shared.AddDeniedException: virtuoso.jdbc4.VirtuosoException: RDFGE: RDF box with a geometry RDF type and a non-geometry content
```

Unless it is a problem in my triple (I don't see where) I think it is a bug.

**Comment by jplu** [comment]
Hi,

I have also a different problem but still related to a Geometry triple:

```
_:2409e0e2fb331ef85d57c46ca5c62aa5 <http://www.w3.org/2003/01/geo/wgs84_pos#geometry> "POINT(9.27542 45.4624)"^^http://www.openlinksw.com/schemas/virtrdf#Geometry
```

Throw me this exception:

```
Exception in thread "main" com.hp.hpl.jena.shared.AddDeniedException: virtuoso.jdbc4.VirtuosoException: GEO11: Valid type of spatial feature is expected (near row 1 col 4 of 'com.hp.hpl.jena.datatypes.BaseDatatype$TypedValue@ce6f1909')
```

**Comment by HughWilliams** [comment]
@jplu: The specific geo spatial type should be specified on the actual values of the geometry rather than the type itself:

SQL> sparql insert into <test_datatype> { http://data.linkedevents.org/location/bikepark/146/geometry http://www.w3.org/2003/01/geo/wgs84_pos#geometry "POINT(9.2027395963669^^http://www.openlinksw.com/schemas/virtrdf#Geometry 45.4480098982521^^http://www.opengis.net/ont/geosparql#wktLiteral)" };

Done. -- 1 msec.
SQL>

SQL> sparql insert into <test_datatype> { _:2409e0e2fb331ef85d57c46ca5c62aa5 http://www.w3.org/2003/01/geo/wgs84_pos#geometry "POINT(9.27542^^http://www.openlinksw.com/schemas/virtrdf#Geometry 45.4624^^http://www.openlinksw.com/schemas/virtrdf#Geometry)" };

Done. -- 4 msec.
SQL>

See:

   http://docs.openlinksw.com/virtuoso/rdfsparqlgeospat.html
   http://virtuoso.openlinksw.com/dataspace/doc/dav/wiki/Main/VirtGeoSPARQLEnhancementDocs

**Comment by jplu** [comment]
Ok thanks Hugh. But that doesn't works for me:

```
sparql insert into { http://data.linkedevents.org/location/bikepark/146/geometry http://www.w3.org/2003/01/geo/wgs84_pos#geometry "POINT(9.2027395963669^^http://www.openlinksw.com/schemas/virtrdf#Geometry 45.4480098982521^^http://www.opengis.net/ont/geosparql#wktLiteral)" };


*** Error 37000: [Virtuoso Driver][Virtuoso Server]SQ074: Line 1: 
at line 1 of Top-Level:
sparql insert into { http://data.linkedevents.org/location/bikepark/146/geometry http://www.w3.org/2003/01/geo/wgs84_pos#geometry "POINT(9.2027395963669^^http://www.openlinksw.com/schemas/virtrdf#Geometry 45.4480098982521^^http://www.opengis.net/ont/geosparql#wktLiteral)" }
```

Or

```
sparql insert into { _:2409e0e2fb331ef85d57c46ca5c62aa5 http://www.w3.org/2003/01/geo/wgs84_pos#geometry "POINT(9.27542^^http://www.openlinksw.com/schemas/virtrdf#Geometry 45.4624^^http://www.openlinksw.com/schemas/virtrdf#Geometry)" };

*** Error 37000: [Virtuoso Driver][Virtuoso Server]SQ074: Line 1: 
at line 8 of Top-Level:
sparql insert into { _:2409e0e2fb331ef85d57c46ca5c62aa5 http://www.w3.org/2003/01/geo/wgs84_pos#geometry "POINT(9.27542^^http://www.openlinksw.com/schemas/virtrdf#Geometry 45.4624^^http://www.openlinksw.com/schemas/virtrdf#Geometry)" }
```

**Comment by HughWilliams** [comment]
The query URIs are missing the angles brackets around them ...

**Comment by jplu** [comment]
Hi @HughWilliams,

I made some more tests and apparently nothing works (see my previous post) with `insert into`. So I used `insert data` and loading the triple:

```
<http://data.linkedevents.org/location/bikepark/146/geometry> <http://www.w3.org/2003/01/geo/wgs84_pos#geometry> "POINT(9.2027395963669 45.4480098982521)"^^http://www.opengis.net/ont/geosparql#wktLiteral
```

is working, see:

```
sparql insert data { GRAPH <http://test.org> {<http://data.linkedevents.org/location/bikepark/146/geometry> <http://www.w3.org/2003/01/geo/wgs84_pos#geometry> "POINT(9.2027395963669 45.4480098982521"^^<http://www.opengis.net/ont/geosparql#wktLiteral>} };

Done. -- 3 msec.
```

And in specifying the type to each component as well:

```
sparql insert data { GRAPH <http://test.org> {<http://data.linkedevents.org/location/bikepark/146/geometry> <http://www.w3.org/2003/01/geo/wgs84_pos#geometry> "POINT(9.2027395963669^^<http://www.openlinksw.com/schemas/virtrdf#Geometry> 45.4480098982521^^<http://www.opengis.net/ont/geosparql#wktLiteral>)"} };

Done. -- 4 msec.
```

But when it is a blank node, it still doesn't works:

```
SQL> sparql insert data { GRAPH <http://test.org> {_:2409e0e2fb331ef85d57c46ca5c62aa5 <http://www.w3.org/2003/01/geo/wgs84_pos#geometry> "POINT(9.2027395963669 45.4480098982521"^^<http://www.opengis.net/ont/geosparql#wktLiteral>} };

*** Error 37000: [Virtuoso Driver][Virtuoso Server]SQ074: Line 1: SP031: SPARQL compiler: Blank node '_:2409e0e2fb331ef85d57c46ca5c62aa5' is not allowed in a constant clause
at line 13 of Top-Level:
sparql insert data { GRAPH <http://test.org> {_:2409e0e2fb331ef85d57c46ca5c62aa5 <http://www.w3.org/2003/01/geo/wgs84_pos#geometry> "POINT(9.2027395963669 45.4480098982521"^^<http://www.opengis.net/ont/geosparql#wktLiteral>} }

SQL> sparql insert data { GRAPH <http://test.org> {_:2409e0e2fb331ef85d57c46ca5c62aa5 <http://www.w3.org/2003/01/geo/wgs84_pos#geometry> "POINT(9.2027395963669 45.4480098982521"^^<http://www.opengis.net/ont/geosparql#wktLiteral>} };

*** Error 37000: [Virtuoso Driver][Virtuoso Server]SQ074: Line 1: SP031: SPARQL compiler: Blank node '_:2409e0e2fb331ef85d57c46ca5c62aa5' is not allowed in a constant clause
at line 14 of Top-Level:
sparql insert data { GRAPH <http://test.org> {_:2409e0e2fb331ef85d57c46ca5c62aa5 <http://www.w3.org/2003/01/geo/wgs84_pos#geometry> "POINT(9.2027395963669 45.4480098982521"^^<http://www.opengis.net/ont/geosparql#wktLiteral>} }
```

Anyway the problem is not coming from when I try to insert a triple in the isql prompt, but when I try to do it from the virtjena drivers (see my two first posts).

Thanks.

**Comment by HughWilliams** [comment]
@jplu:  Why do you say the problem is not coming from isql when the error is reported via isql also ?

**Comment by jplu** [comment]
Because the error message from Virtjena and isql are not the same so I suppose it is a different problem, maybe worth it to open a separate issue for that ?

**Comment by jplu** [comment]
Hi @HughWilliams 

I just saw there have been some updates in the virtjena source code, is-it possible to provide a new generated jar which contain those changes ? To see if it solve my problem.

**Comment by HughWilliams** [comment]
@jplu: The latest jena code is still to be merged to the open source develop/7 tree, but in the interim a prebuilt version of the latest Jena provider can be downloaded from:

   ftp://download.openlinksw.com/support/virtuoso/java/virt_jena2.jar

**Comment by jplu** [comment]
Thanks @HughWilliams, I test it ASAP, and I let you know if this version solve my problem. If not I will wait the final merge.

**Comment by Aklakan** [comment]
Hi Hugh, I just tested your jar file and for me it solved the problem; with this driver, the geo-triples that failed to insert now end up in the store.

**Comment by HughWilliams** [comment]
@jplu have you tested the updated Jena jar to confirm it is solved your problem, such that this git issue can be closed ?

**Comment by jplu** [comment]
Yes @HughWilliams it is ok, I just tested right now and it works.

Thanks.
